### ISSUE TITLE
License identifier does not match License

### ISSUE THREAD

**Issue by johanneslotz** [HumanSignal/label-studio-tools#67]
Hi, 

I just observed that the license identifier in PyPi (OSI Approved :: MIT License) does not match the license file (Apache). I am not sure if the maintainers of this project also manage the PyPi project, but would be glad if this could be fixed as it returns incorrect reports in pip-licenses.

https://pypi.org/project/label-studio-tools/

Thanks!
Johannes

CC: @niklub, who seems to be the maintainer in PyPi

**Comment by makseq** [comment]
Thanks for reaching us about the license. We are moving this repo to Label Studio SDK and this lib will be a part of SDK. So, we will update the license as well.

**Comment by johanneslotz** [comment]
Awesome, thanks!
